services:
  frontend:
    build: ./frontend
    container_name: url_shortener-frontend
    ports:
      - "8083:80"
    networks:
      - default

  backend:
    build: ./backend
    container_name: url_shortener-backend
    ports:
      - "3002:3002"
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: url_shortener-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - default

networks:
  default:

